### ISSUE TITLE
Unable to fetch data from arbitrum - Could not detect network Error: noNetwork

### ISSUE THREAD

**Issue by saadjhk** [subquery/subql#1939] opened 2023-08-11 09:06 UTC
### Prerequisites

* [X] Are you running the latest version(s)?
* [X] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [X] Did you search for an existing issue or pull request?

### Description

I can not make a call to retrieve data from a getter from arbitrum blockchian, all JsonRpcProviders of ethereum returns the same error which is "Could not detect network Error: noNetwork"

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** Ubuntu 23.04, Docker, Node 16
**Query Version:** 2.5.0
**Indexer Version:** 2.10.0
**Network Details:**
  * Arbitrum
  * Arbitrum dictionary

### Steps to Reproduce

1. Setup project
2. query chain in a handler
3. errors out

**Expected behavior:** connection to the chain is sucessful

**Actual behavior:** can not access network from docker on subql-node ethereum

**Comment by stwiname** [comment] 2023-08-14 02:09
@saadjhk do you mind sharing the RPC provider? You don't need to share any api keys.

Sometimes they behave slightly differently and we can check compatibility if we know

**Comment by saadjhk** [comment] 2023-08-14 09:39
I tried with almost 20 different RPC providers listed on https://chainlist.org for arbitrum

**Comment by saadjhk** [comment] 2023-08-14 09:40
I also want to mention that this happens when i try to instantiate an ethereum provider within an event handler and then query a contract using that provider

**Comment by stwiname** [comment] 2023-08-16 04:55
Are you able to share an example project?

I can't reproduce this at all, every endpoint i try works.



If you're trying to make network requests from a handler you need the `--unsafe` flag. Otherwise you can use the injected provider rather than creating your own instance.

**Comment by stwiname** [comment] 2024-05-22 01:51
I cannot reproduce this. Closing unless there is a reproducible example give

**Closed by stwiname** 2024-05-22 01:51 UTC
Labels: ethereum
