### ISSUE TITLE
Update @subql/query GraphQL Playground

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1808] opened 2023-06-19 06:37 UTC
### Description

We have polished and updated a new version of the SubQuery GraphQL interface https://github.com/subquery/subql-ui-components/pull/81

Please update the interface in the query service to use this so all GraphQL interfaces are the same

**Comment by stwiname** [comment] 2023-06-20 22:31
Duplicate of https://github.com/subquery/subql/issues/1515

**Closed by stwiname** 2023-06-20 22:31 UTC
Labels: enhancement, Query Service
