### ISSUE TITLE
Support best block with thread worker

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1672] opened 2023-05-09 23:58 UTC
### Description

In the latest version, if you try to enable worker + best block, the node will panic with
`Sorry, best block feature is not supported with workers yet.","stack":"Error: Sorry, best block feature is not supported with workers yet`

### Details

Support best block with thread worker

**Comment by stwiname** [comment] 2023-05-10 00:44
Duplicate of https://github.com/subquery/subql/issues/1399

**Closed by stwiname** 2023-05-10 00:44 UTC
Labels: New Feature
