### ISSUE TITLE
Can't run subql-query locally

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1125] opened 2022-06-25 12:42 UTC
Nodejs: v16.13.0

$ npm -g i @subql/query@1.2.0

$ subql-query 

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'apollo-server-core'
Require stack:
- /Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/graphql/graphql.module.js
- /Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/app.module.js
- /Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/main.js
- /Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/bin/run
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/graphql/graphql.module.js:21:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/graphql/graphql.module.js',
    '/Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/app.module.js',
    '/Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/dist/main.js',
    '/Users/ian/.nvm_arm64/versions/node/v16.13.0/lib/node_modules/@subql/query/bin/run'
  ]
}
```

**Comment by jiqiang90** [comment] 2022-07-04 04:04
<img width="969" alt="Screen Shot 2022-07-04 at 4 03 15 PM" src="https://user-images.githubusercontent.com/10431657/177079547-a21ffeba-598e-486a-a424-1bb90c78c88d.png">

v1.2.0 works for me in local, I'm using 16.14.0

**Comment by stwiname** [comment] 2022-09-09 02:32
Closing as not reproducible

**Closed by stwiname** 2022-09-09 02:32 UTC
