### ISSUE TITLE
Unable to fetch from contract BEVM 

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2363] opened 2024-04-19 04:42 UTC
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

When querying an EVM contract on the SDK, would respond with null values.

### Details
`@subql/node-ethereum`

### Steps to Reproduce

When using contract `0xfBA94Cf31f47966D89EF689edF59bc37fC84ca9c` on BEVM the contract calls would return 
```
[{"type":"BigNumber","hex":"0x00"},"0x0000000000000000000000000000000000000000","0x","0x",{"type":"BigNumber","hex":"0x00"},0,{"type":"BigNumber","hex":"0x00"},{"type":"BigNumber","hex":"0x00"},0,"0x"]
```

Whereas, when using eth95 to query this contract

```
["5","0x8c951f58F63C0018BFBb47A29e55e84507eD63Bd",
"0x746231706d34647767713975746d68797638306c38306479737a647833376e376763666638613835747830326776776b75767a73707371736b6676713676","0x4d4147494352554e4553494f","1","0","100100000000000","100100000000","0","0x"]
```

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment] 2024-04-21 21:35
Is there an example project to reproduce this? It seems like an ABI decoding issue

**Comment by bz888** [comment] 2024-04-26 06:40
Example project: https://github.com/bz888/bevm-subql-example

**Comment by stwiname** [comment] 2024-04-29 01:25
Most likely due to the contract factory called outside of the handler https://github.com/bz888/bevm-subql-example/blob/main/src/mappings/mappingHandlers.ts#L5

I was unable to reproduce because of issues with the endpoint

Closing, feel free to reopen if can still be reproduced

**Closed by stwiname** 2024-04-29 01:25 UTC
