### ISSUE TITLE
Codegen path bug

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1439] opened 2022-11-29 01:27 UTC
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

When point to specific manifest, it failed to codegen due to path issue. 

```
jiatwork@MacBook-Pro-4 multi-networks-transfers % yarn codegen -l project-kusama.yaml 
yarn run v1.22.19
$ subql codegen -l project-kusama.yaml
===============================
---------Subql Codegen---------
===============================
Failed to prepare /Users/jiatwork/subql4/multiNetworks/multi-networks-transfers/project-kusama.yaml/src/types/models
```

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment] 2022-12-01 23:17
I think this is a duplicate of https://github.com/subquery/subql/issues/1332

**Closed by stwiname** 2022-12-01 23:17 UTC
